# Generated by Django 5.2.8 on 2025-12-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opt_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Оптова Вартість'),
        ),
    ]
